---
experiment:
  name: procc/mitstates
dataset:
  data_dir: mit-states
  dataset: mitstates
  splitname: compositional-split-natural
model_params:
  model: procc
  gumbel: false
  partial: false
  dropout: true
  norm: true
  image_extractor: resnet18_s
  train_only: false
  static_inp: false
training:
  step_obj: 50
  step_attr: 100
  step_normal: 25
  batch_size: 256
  eval_val_every: 5
  load:
  lr: 5.0e-05
  lr_ft: 1.0e-05
  wd: 5.0e-05
  lrg: 5.0e-6
  max_epochs: 600
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 512
  test_set: val
  topk: 1
  workers: 8
  update_features: false
  freeze_features: false

