---
experiment:
  name: procc/utzappos
dataset:
  data_dir: ut-zap50k
  dataset: utzappos
  splitname: compositional-split-natural
model_params:
  model: procc
  partial: false
  gumbel: false
  dropout: true
  norm: true
  fc_emb: 768,1024,1200
  eval_type: otherdist
  emb_init: word2vec
  emb_dim: 300
  image_extractor: resnet18_s
  train_only: true
  static_inp: false
  composition: mlp_add
training:
  step_obj: 40
  step_attr: 100
  step_normal: 20
  batch_size: 128
  eval_val_every: 1
  load:
  lr: 5.0e-05
  lr_ft: 1.0e-05
  wd: 5.0e-05
  lrg: 5.0e-6
  margin: 0.5
  max_epochs: 1000
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 512
  test_set: val
  topk: 1
  workers: 8
  update_features: false
  freeze_features: false
